<a href="https://colab.research.google.com/github/cowbow244/Data-Analysis-with-Open-Source/blob/main/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_5%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 오픈소스 기반 데이터 분석 5강 - 데이터 저장

## 5-1 CSV 형식 저장

In [8]:
import pandas as pd

data = {
    'student_id': [101, 102, 103, 104, 105],
    'database_score': [85, 76, 92, 63, 88],
    'cloudcomputing_score': [78, 82, 95, 70, 84],
    'python_score': [92, 78, 85, 75, 91],
    'watch_rate': [0.95, 0.87, 0.99, 0.80, 0.93]
}
## DataFrame 생성
df = pd.DataFrame(data)

## CSV 형식 저장
df.to_csv('student_5-1.csv', encoding = 'utf-8', index = False)

#print(pd.read_csv('student_5-1.csv', encoding = 'utf-8'))

   student_id  database_score  cloudcomputing_score  python_score  watch_rate
0         101              85                    78            92        0.95
1         102              76                    82            78        0.87
2         103              92                    95            85        0.99
3         104              63                    70            75        0.80
4         105              88                    84            91        0.93

## 5-2 JSON 형식 저장

In [26]:
### 라이브러리 임포트
import json
import pandas as pd

data = {
    "이름": "홍길동",
    "나이": 25,
    "거주지": "서울",
    "관심사": ["프로그래밍", "데이터 분석", "여행"]
}

## json.dump를 이용한 저장
with open('output.json', 'w', encoding = 'utf-8') as f:
    json.dump(data, f, indent=4, ensure_ascii=False)

## DataFrame을 이용한 저장
df = pd.DataFrame([data])   #data가 딕셔너리 단위여서 그냥 (data)하면 관심사별로 3명분의 내용이 만들어짐, 리스트로 묶으면 data의 형식과 동일하게 나옴
df.to_json('output_pd.json', orient = 'records', indent = 4, force_ascii = False) #records시 각 행(리코드==row)단위 형태, 'colums'시 각 열(컬럼)별로

## 5-3 Pandas Dataframe 데이터 추출

In [27]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터학", "경영학", "농학", "교육학", "영어영문학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}
df = pd.DataFrame(data)

## DataFrame 인덱스 출력
print(df.index)

## DataFrame 컬럼 출력
print(df.columns)

## DataFrame 행 출력
print(df.values.tolist())
print(df.values)
#차이점 : 둘다 화면상에는 별 차이 없지만 tolist()를 하면 파이썬의 리스트형태로 만들어준다.

## DataFrame 값 출력
print(df.values.flatten()) #구조화 되어 있는 걸 구조를 뭉개트리고 쭉 나열시키는 함수가 faltten()

RangeIndex(start=0, stop=5, step=1)
Index(['이름', '학년', '학점', '학과', '동아리'], dtype='object')
[['김철수', 1, 4.2, '컴퓨터학', '프로그래밍'], ['이영희', 2, 3.8, '경영학', '독서토론'], ['박민수', 3, 4.5, '농학', '로봇공학'], ['최지훈', 4, 3.9, '교육학', '봉사활동'], ['정소희', 2, 3.5, '영어영문학', '음악감상']]
[['김철수' 1 4.2 '컴퓨터학' '프로그래밍']
 ['이영희' 2 3.8 '경영학' '독서토론']
 ['박민수' 3 4.5 '농학' '로봇공학']
 ['최지훈' 4 3.9 '교육학' '봉사활동']
 ['정소희' 2 3.5 '영어영문학' '음악감상']]
['김철수' 1 4.2 '컴퓨터학' '프로그래밍' '이영희' 2 3.8 '경영학' '독서토론' '박민수' 3 4.5 '농학'
 '로봇공학' '최지훈' 4 3.9 '교육학' '봉사활동' '정소희' 2 3.5 '영어영문학' '음악감상']

## 5-4 DataFrame 생성 방법

In [28]:
import pandas as pd
import json

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

## 딕셔너리, csv, json으로 부터 DataFrame 생성
df1 = pd.DataFrame.from_dict(data)
df2 = pd.read_csv('students.csv')
df3 = pd.read_json('students.json')

## 세가지 방법 결과 비교, shape은 DataFrame의 행과 열이 몇개씩 있는 지를 알려주는 함수
print(df1.shape)
print(df2.shape)
print(df3.shape)

(5, 5)
(5, 5)
(5, 5)

## 5-5 DataFrame 저장 방법

In [29]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

## Dataframe 생성
df = pd.DataFrame.from_dict(data)

## CSV, JSON 형식으로 저장
df.to_csv('student_5-5.csv')
df.to_json('student_5-5.json')

## HTML 형식으로 저장
html_table = df.to_html()
print(html_table)
with open('student_5-5.html', 'w') as f:
    f.write(html_table)


##  df.to_html('A.html') 형식도 가능
##  open의 장점 = HTML 코드 수정(커스텀)판다스가 만들어준 기본 HTML 테이블에 개발자가 직접 스타일(CSS)이나 다른 HTML 태그를 앞뒤로 붙여서 꾸민 다음
##  저장하고 싶을 때 with open() 방식을 활용하기도 합니다.

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>이름</th>
      <th>학년</th>
      <th>학점</th>
      <th>학과</th>
      <th>동아리</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>김철수</td>
      <td>1</td>
      <td>4.2</td>
      <td>컴퓨터공학</td>
      <td>프로그래밍</td>
    </tr>
    <tr>
      <th>1</th>
      <td>이영희</td>
      <td>2</td>
      <td>3.8</td>
      <td>경영학</td>
      <td>독서토론</td>
    </tr>
    <tr>
      <th>2</th>
      <td>박민수</td>
      <td>3</td>
      <td>4.5</td>
      <td>전자공학</td>
      <td>로봇공학</td>
    </tr>
    <tr>
      <th>3</th>
      <td>최지훈</td>
      <td>4</td>
      <td>3.9</td>
      <td>의학</td>
      <td>봉사활동</td>
    </tr>
    <tr>
      <th>4</th>
      <td>정소희</td>
      <td>2</td>
      <td>3.5</td>
      <td>심리학</td>
      <td>음악감상</td>
    </tr>
  </tbody>
</table>

"\ndf.to_html('A.html') 형식도 가능 \nopen의 장점 = HTML 코드 수정(커스텀)판다스가 만들어준 기본 HTML 테이블에 개발자가 직접 스타일(CSS)이나 다른 HTML 태그를 앞뒤로 붙여서 꾸민 다음 \n저장하고 싶을 때 with open() 방식을 활용하기도 합니다.\n"

## 5-6 실습 시나리오

## 데이터 수집

In [38]:
import requests

url = "https://apis.data.go.kr/B552584/ArpltnInforInqireSvc/getCtprvnRltmMesureDnsty"
api_key = ''

params = {
    'serviceKey': api_key,
    'returnType': 'json',
    'numOfRows': '100',
    'pageNo': '1',
    'sidoName': '경기',
    'ver': '1.0'
}

## 데이터 수집
response = requests.get(url, params=params)

## 호출 성공/실패 출력
print(response.json())

{'response': {'body': {'totalCount': 126, 'items': [{'so2Grade': '1', 'coFlag': None, 'khaiValue': '73', 'so2Value': '0.004', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '48', 'khaiGrade': '2', 'pm25Value': '30', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.015', 'stationName': '소사본동', 'pm10Grade': '2', 'o3Value': '0.056'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '82', 'so2Value': '0.004', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '27', 'khaiGrade': '2', 'pm25Value': '14', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.012', 'stationName': '내동', 'pm10Grade': '2', 'o3Value': '0.068'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '75', 'so2Value': '0.004', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '42', 'khaiGrade': '2', 'pm25Value': '20', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.011', 'stationName': '중2동', 'pm10Grade': '2', 'o3Value': '0.059'}, {'so2Grade': None, 'coFlag': None, 'khaiValue': None, 'so2Value': None, 'coValue': None, 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': None, 'pm10Value': None, 'khaiGrade': None, 'pm25Value': None, 'sidoName': '경기', 'no2Flag': None, 'no2Grade': None, 'o3Flag': None, 'pm25Grade': None, 'so2Flag': None, 'dataTime': None, 'coGrade': None, 'no2Value': None, 'stationName': '오정동', 'pm10Grade': None, 'o3Value': None}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '68', 'so2Value': '0.004', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '48', 'khaiGrade': '2', 'pm25Value': '21', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.016', 'stationName': '송내대로(중동)', 'pm10Grade': '2', 'o3Value': '0.048'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '74', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '40', 'khaiGrade': '2', 'pm25Value': '17', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.021', 'stationName': '중앙대로(고잔동)', 'pm10Grade': '2', 'o3Value': '0.053'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '69', 'so2Value': '0.003', 'coValue': '0.6', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '46', 'khaiGrade': '2', 'pm25Value': '27', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.028', 'stationName': '별양동', 'pm10Grade': '2', 'o3Value': '0.052'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '63', 'so2Value': '0.002', 'coValue': '0.6', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '35', 'khaiGrade': '2', 'pm25Value': '16', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.028', 'stationName': '과천동', 'pm10Grade': '2', 'o3Value': '0.045'}, {'so2Grade': None, 'coFlag': '통신장애', 'khaiValue': '-', 'so2Value': '-', 'coValue': '-', 'pm25Flag': '통신장애', 'pm10Flag': '통신장애', 'o3Grade': None, 'pm10Value': '-', 'khaiGrade': None, 'pm25Value': '-', 'sidoName': '경기', 'no2Flag': '통신장애', 'no2Grade': None, 'o3Flag': '통신장애', 'pm25Grade': None, 'so2Flag': '통신장애', 'dataTime': '2026-10-10 20:00', 'coGrade': None, 'no2Value': '-', 'stationName': '교문동', 'pm10Grade': None, 'o3Value': '-'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '59', 'so2Value': '0.004', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '36', 'khaiGrade': '2', 'pm25Value': '20', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.024', 'stationName': '동구동', 'pm10Grade': '2', 'o3Value': '0.036'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '83', 'so2Value': '0.003', 'coValue': '0.6', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '64', 'khaiGrade': '2', 'pm25Value': '32', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.023', 'stationName': '부곡3동', 'pm10Grade': '2', 'o3Value': '0.069'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '78', 'so2Value': '0.003', 'coValue': '0.6', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '50', 'khaiGrade': '2', 'pm25Value': '23', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.023', 'stationName': '고천동', 'pm10Grade': '2', 'o3Value': '0.063'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '82', 'so2Value': '0.004', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '32', 'khaiGrade': '2', 'pm25Value': '17', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.026', 'stationName': '정왕동', 'pm10Grade': '2', 'o3Value': '0.051'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '87', 'so2Value': '0.004', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '39', 'khaiGrade': '2', 'pm25Value': '15', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.013', 'stationName': '시화산단', 'pm10Grade': '2', 'o3Value': '0.064'}, {'so2Grade': None, 'coFlag': None, 'khaiValue': None, 'so2Value': None, 'coValue': None, 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': None, 'pm10Value': None, 'khaiGrade': None, 'pm25Value': None, 'sidoName': '경기', 'no2Flag': None, 'no2Grade': None, 'o3Flag': None, 'pm25Grade': None, 'so2Flag': None, 'dataTime': None, 'coGrade': None, 'no2Value': None, 'stationName': '대야동', 'pm10Grade': None, 'o3Value': None}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '85', 'so2Value': '0.003', 'coValue': '0.6', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '53', 'khaiGrade': '2', 'pm25Value': '30', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '2', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.051', 'stationName': '목감동', 'pm10Grade': '2', 'o3Value': '0.039'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '77', 'so2Value': '0.004', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '48', 'khaiGrade': '2', 'pm25Value': '29', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.024', 'stationName': '장현동', 'pm10Grade': '2', 'o3Value': '0.054'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '87', 'so2Value': '0.004', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '33', 'khaiGrade': '2', 'pm25Value': '24', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.015', 'stationName': '서해안로', 'pm10Grade': '2', 'o3Value': '0.055'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '77', 'so2Value': '0.004', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '35', 'khaiGrade': '2', 'pm25Value': '20', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.017', 'stationName': '배곧동', 'pm10Grade': '2', 'o3Value': '0.058'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '66', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '27', 'khaiGrade': '2', 'pm25Value': '20', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.017', 'stationName': '금곡동', 'pm10Grade': '1', 'o3Value': '0.049'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '73', 'so2Value': '0.004', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '25', 'khaiGrade': '2', 'pm25Value': '15', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.009', 'stationName': '오남읍', 'pm10Grade': '2', 'o3Value': '0.057'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '64', 'so2Value': '0.003', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '34', 'khaiGrade': '2', 'pm25Value': '22', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.021', 'stationName': '별내동', 'pm10Grade': '2', 'o3Value': '0.046'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '65', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '37', 'khaiGrade': '2', 'pm25Value': '16', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.012', 'stationName': '화도읍', 'pm10Grade': '2', 'o3Value': '0.047'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '62', 'so2Value': '0.003', 'coValue': '0.6', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '45', 'khaiGrade': '2', 'pm25Value': '25', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '2', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.034', 'stationName': '경춘로', 'pm10Grade': '2', 'o3Value': '0.026'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '66', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '23', 'khaiGrade': '2', 'pm25Value': '17', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.014', 'stationName': '와부읍', 'pm10Grade': '1', 'o3Value': '0.048'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '80', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '39', 'khaiGrade': '2', 'pm25Value': '21', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.011', 'stationName': '진접읍', 'pm10Grade': '2', 'o3Value': '0.066'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '85', 'so2Value': '0.003', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '61', 'khaiGrade': '2', 'pm25Value': '44', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.020', 'stationName': '비전동', 'pm10Grade': '2', 'o3Value': '0.072'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '100', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '82', 'khaiGrade': '2', 'pm25Value': '45', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.011', 'stationName': '안중', 'pm10Grade': '2', 'o3Value': '0.088'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '113', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '3', 'pm10Value': '79', 'khaiGrade': '3', 'pm25Value': '44', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.011', 'stationName': '평택항', 'pm10Grade': '2', 'o3Value': '0.095'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '103', 'so2Value': '0.003', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '3', 'pm10Value': '81', 'khaiGrade': '3', 'pm25Value': '43', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.021', 'stationName': '송북동', 'pm10Grade': '2', 'o3Value': '0.091'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '101', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '81', 'khaiGrade': '3', 'pm25Value': '51', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '3', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.012', 'stationName': '청북읍', 'pm10Grade': '2', 'o3Value': '0.088'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '119', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '3', 'pm10Value': '64', 'khaiGrade': '3', 'pm25Value': '40', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.013', 'stationName': '고덕동', 'pm10Grade': '2', 'o3Value': '0.097'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '-', 'so2Value': '0.002', 'coValue': '0.7', 'pm25Flag': '통신장애', 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '55', 'khaiGrade': None, 'pm25Value': '-', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': None, 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.016', 'stationName': '금촌동', 'pm10Grade': '2', 'o3Value': '0.055'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '75', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '38', 'khaiGrade': '2', 'pm25Value': '23', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.007', 'stationName': '운정', 'pm10Grade': '2', 'o3Value': '0.059'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '-', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': '통신장애', 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '53', 'khaiGrade': None, 'pm25Value': '-', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': None, 'so2Flag': None, 'dataTime': '2026-10-10 21:00', 'coGrade': '1', 'no2Value': '0.003', 'stationName': '파주', 'pm10Grade': '2', 'o3Value': '0.063'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '64', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '28', 'khaiGrade': '2', 'pm25Value': '16', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.007', 'stationName': '파주읍', 'pm10Grade': '1', 'o3Value': '0.046'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '65', 'so2Value': '0.003', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '45', 'khaiGrade': '2', 'pm25Value': '20', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.012', 'stationName': '행신동', 'pm10Grade': '2', 'o3Value': '0.047'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '69', 'so2Value': '0.003', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '74', 'khaiGrade': '2', 'pm25Value': '17', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.013', 'stationName': '식사동', 'pm10Grade': '2', 'o3Value': '0.053'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '68', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '47', 'khaiGrade': '2', 'pm25Value': '18', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.008', 'stationName': '백마로(마두역)', 'pm10Grade': '2', 'o3Value': '0.051'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '-', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': '통신장애', 'pm10Flag': '통신장애', 'o3Grade': '1', 'pm10Value': '-', 'khaiGrade': None, 'pm25Value': '-', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': None, 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.028', 'stationName': '신원동', 'pm10Grade': None, 'o3Value': '0.029'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '71', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '49', 'khaiGrade': '2', 'pm25Value': '25', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.008', 'stationName': '주엽동', 'pm10Grade': '2', 'o3Value': '0.055'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '61', 'so2Value': '0.002', 'coValue': '0.6', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '48', 'khaiGrade': '2', 'pm25Value': '29', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.019', 'stationName': '경안동', 'pm10Grade': '2', 'o3Value': '0.042'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '59', 'so2Value': '0.002', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '27', 'khaiGrade': '2', 'pm25Value': '11', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.018', 'stationName': '오포1동', 'pm10Grade': '2', 'o3Value': '0.040'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '65', 'so2Value': '0.002', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '24', 'khaiGrade': '2', 'pm25Value': '3', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.007', 'stationName': '곤지암', 'pm10Grade': '1', 'o3Value': '0.047'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '59', 'so2Value': '0.002', 'coValue': '0.6', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '30', 'khaiGrade': '2', 'pm25Value': '20', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.027', 'stationName': '김량장동', 'pm10Grade': '1', 'o3Value': '0.032'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '68', 'so2Value': '0.002', 'coValue': '0.6', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '28', 'khaiGrade': '2', 'pm25Value': '21', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.027', 'stationName': '수지', 'pm10Grade': '2', 'o3Value': '0.051'}, {'so2Grade': '1', 'coFlag': None,

## 데이터 프레임 생성

In [50]:
import pandas as pd

## requests로부터 response, body, item 항목 읽기
data = response.json()['response']['body']['items']
print(type(data))
print(len(data))
print(data[0])

df = pd.DataFrame(data)
##  df  전체를 표로 출력
df['pm25Grade']

<class 'list'>
100
{'so2Grade': '1', 'coFlag': None, 'khaiValue': '73', 'so2Value': '0.004', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '48', 'khaiGrade': '2', 'pm25Value': '30', 'sidoName': '경기', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-10-10 20:00', 'coGrade': '1', 'no2Value': '0.015', 'stationName': '소사본동', 'pm10Grade': '2', 'o3Value': '0.056'}

0        2
1        1
2        2
3     None
4        2
      ...
95       2
96       2
97       2
98       2
99       2
Name: pm25Grade, Length: 100, dtype: object

## 다양항 형식으로 데이터 저장

In [53]:
df.to_csv('air_pollution.csv', index=False, encoding='utf-8')

## JSON 형식 데이터 저장
df.to_json('air_pollution.json', indent = 4, force_ascii = False)

## EXCEL 형식 데이터 저장
df.to_excel('air_pollution.xlsx', index=False)

## HTML 형식 데이터 저장
df.to_html('air_pollution.html')